//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WitnessVisualizer.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WitnessVisualizer.Resources.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Broken 的本地化字符串。
        /// </summary>
        internal static string Broken {
            get {
                return ResourceManager.GetString("Broken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Circle 的本地化字符串。
        /// </summary>
        internal static string Circle {
            get {
                return ResourceManager.GetString("Circle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Eliminator 的本地化字符串。
        /// </summary>
        internal static string Eliminator {
            get {
                return ResourceManager.GetString("Eliminator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Emoji 的本地化字符串。
        /// </summary>
        internal static string Emoji {
            get {
                return ResourceManager.GetString("Emoji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Empty 的本地化字符串。
        /// </summary>
        internal static string Empty {
            get {
                return ResourceManager.GetString("Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EndD 的本地化字符串。
        /// </summary>
        internal static string EndD {
            get {
                return ResourceManager.GetString("EndD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EndL 的本地化字符串。
        /// </summary>
        internal static string EndL {
            get {
                return ResourceManager.GetString("EndL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EndR 的本地化字符串。
        /// </summary>
        internal static string EndR {
            get {
                return ResourceManager.GetString("EndR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EndU 的本地化字符串。
        /// </summary>
        internal static string EndU {
            get {
                return ResourceManager.GetString("EndU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [Error] Please name the object using the text box. 的本地化字符串。
        /// </summary>
        internal static string Errors_NameEmpty {
            get {
                return ResourceManager.GetString("Errors.NameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [Error] Please select an edge first. 的本地化字符串。
        /// </summary>
        internal static string Errors_NoEdge {
            get {
                return ResourceManager.GetString("Errors.NoEdge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [Error] Please select at least an element first. 的本地化字符串。
        /// </summary>
        internal static string Errors_NoElement {
            get {
                return ResourceManager.GetString("Errors.NoElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [Error] Please select at least an tetris element first. 的本地化字符串。
        /// </summary>
        internal static string Errors_NoTetris {
            get {
                return ResourceManager.GetString("Errors.NoTetris", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hint 的本地化字符串。
        /// </summary>
        internal static string Hint {
            get {
                return ResourceManager.GetString("Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hollow Tetris 的本地化字符串。
        /// </summary>
        internal static string HollowTetris {
            get {
                return ResourceManager.GetString("HollowTetris", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Added {0} Items. 的本地化字符串。
        /// </summary>
        internal static string Info_AddItems {
            get {
                return ResourceManager.GetString("Info.AddItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please (use Ctrl) to select two decorations to combine them. 的本地化字符串。
        /// </summary>
        internal static string Info_Combine {
            get {
                return ResourceManager.GetString("Info.Combine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enter the angle (clockwise) in degrees: 的本地化字符串。
        /// </summary>
        internal static string Info_EnterDegrees {
            get {
                return ResourceManager.GetString("Info.EnterDegrees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter a float scale factor (e.g., 2.0 or 0.5). 的本地化字符串。
        /// </summary>
        internal static string Info_FloatScale {
            get {
                return ResourceManager.GetString("Info.FloatScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You cannot undo this. 的本地化字符串。
        /// </summary>
        internal static string Info_NoUndo {
            get {
                return ResourceManager.GetString("Info.NoUndo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure you want to delete  的本地化字符串。
        /// </summary>
        internal static string Info_ToDelete {
            get {
                return ResourceManager.GetString("Info.ToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Metadata 的本地化字符串。
        /// </summary>
        internal static string MetaData {
            get {
                return ResourceManager.GetString("MetaData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No Property Shown 的本地化字符串。
        /// </summary>
        internal static string NoPropertyShown {
            get {
                return ResourceManager.GetString("NoPropertyShown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Painter 的本地化字符串。
        /// </summary>
        internal static string Painter {
            get {
                return ResourceManager.GetString("Painter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Painting Mode Control 的本地化字符串。
        /// </summary>
        internal static string PaintingModeControl {
            get {
                return ResourceManager.GetString("PaintingModeControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Point 的本地化字符串。
        /// </summary>
        internal static string Point {
            get {
                return ResourceManager.GetString("Point", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pointer 的本地化字符串。
        /// </summary>
        internal static string Pointer {
            get {
                return ResourceManager.GetString("Pointer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Puzzle Title 的本地化字符串。
        /// </summary>
        internal static string PuzzleTitle {
            get {
                return ResourceManager.GetString("PuzzleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Redo 的本地化字符串。
        /// </summary>
        internal static string Redo {
            get {
                return ResourceManager.GetString("Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ring 的本地化字符串。
        /// </summary>
        internal static string Ring {
            get {
                return ResourceManager.GetString("Ring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Skew Hollow Tetris 的本地化字符串。
        /// </summary>
        internal static string SkewHollowTetris {
            get {
                return ResourceManager.GetString("SkewHollowTetris", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Skew Tetris 的本地化字符串。
        /// </summary>
        internal static string SkewTetris {
            get {
                return ResourceManager.GetString("SkewTetris", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Square 的本地化字符串。
        /// </summary>
        internal static string Square {
            get {
                return ResourceManager.GetString("Square", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Star 的本地化字符串。
        /// </summary>
        internal static string Star {
            get {
                return ResourceManager.GetString("Star", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start 的本地化字符串。
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Symbol 的本地化字符串。
        /// </summary>
        internal static string Symbol {
            get {
                return ResourceManager.GetString("Symbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tetris 的本地化字符串。
        /// </summary>
        internal static string Tetris {
            get {
                return ResourceManager.GetString("Tetris", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Text 的本地化字符串。
        /// </summary>
        internal static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Triangle 1 的本地化字符串。
        /// </summary>
        internal static string Triangle1 {
            get {
                return ResourceManager.GetString("Triangle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Triangle 2 的本地化字符串。
        /// </summary>
        internal static string Triangle2 {
            get {
                return ResourceManager.GetString("Triangle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Triangle 3 的本地化字符串。
        /// </summary>
        internal static string Triangle3 {
            get {
                return ResourceManager.GetString("Triangle3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Triangle 4 的本地化字符串。
        /// </summary>
        internal static string Triangle4 {
            get {
                return ResourceManager.GetString("Triangle4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Triangle 5 的本地化字符串。
        /// </summary>
        internal static string Triangle5 {
            get {
                return ResourceManager.GetString("Triangle5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Undo 的本地化字符串。
        /// </summary>
        internal static string Undo {
            get {
                return ResourceManager.GetString("Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Paint {0} with {1}. 的本地化字符串。
        /// </summary>
        internal static string Undo_Paint {
            get {
                return ResourceManager.GetString("Undo.Paint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Warning 的本地化字符串。
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [Warning] Corrupted Toolkit. Click YES to create a new one. 的本地化字符串。
        /// </summary>
        internal static string Warnings_CorruptedToolkit {
            get {
                return ResourceManager.GetString("Warnings.CorruptedToolkit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [Warning] Failed to load  的本地化字符串。
        /// </summary>
        internal static string Warnings_FailToLoad {
            get {
                return ResourceManager.GetString("Warnings.FailToLoad", resourceCulture);
            }
        }
    }
}
