//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WitnessVisualizer.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WitnessVisualizer.Resources.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrow.
        /// </summary>
        internal static string Arrow {
            get {
                return ResourceManager.GetString("Arrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Box.
        /// </summary>
        internal static string Box {
            get {
                return ResourceManager.GetString("Box", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broken.
        /// </summary>
        internal static string Broken {
            get {
                return ResourceManager.GetString("Broken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circle.
        /// </summary>
        internal static string Circle {
            get {
                return ResourceManager.GetString("Circle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeltaX.
        /// </summary>
        internal static string DeltaX {
            get {
                return ResourceManager.GetString("DeltaX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeltaY.
        /// </summary>
        internal static string DeltaY {
            get {
                return ResourceManager.GetString("DeltaY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminator.
        /// </summary>
        internal static string Eliminator {
            get {
                return ResourceManager.GetString("Eliminator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emoji.
        /// </summary>
        internal static string Emoji {
            get {
                return ResourceManager.GetString("Emoji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty.
        /// </summary>
        internal static string Empty {
            get {
                return ResourceManager.GetString("Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EndD.
        /// </summary>
        internal static string EndD {
            get {
                return ResourceManager.GetString("EndD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EndL.
        /// </summary>
        internal static string EndL {
            get {
                return ResourceManager.GetString("EndL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EndR.
        /// </summary>
        internal static string EndR {
            get {
                return ResourceManager.GetString("EndR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EndU.
        /// </summary>
        internal static string EndU {
            get {
                return ResourceManager.GetString("EndU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Error] Please name the object using the text box..
        /// </summary>
        internal static string Errors_NameEmpty {
            get {
                return ResourceManager.GetString("Errors.NameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Error] Please select an edge first..
        /// </summary>
        internal static string Errors_NoEdge {
            get {
                return ResourceManager.GetString("Errors.NoEdge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Error] Please select at least an element first..
        /// </summary>
        internal static string Errors_NoElement {
            get {
                return ResourceManager.GetString("Errors.NoElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Error] Please select at least an tetris element first..
        /// </summary>
        internal static string Errors_NoTetris {
            get {
                return ResourceManager.GetString("Errors.NoTetris", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExtraScale.
        /// </summary>
        internal static string ExtraScale {
            get {
                return ResourceManager.GetString("ExtraScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hint.
        /// </summary>
        internal static string Hint {
            get {
                return ResourceManager.GetString("Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hollow Tetris.
        /// </summary>
        internal static string HollowTetris {
            get {
                return ResourceManager.GetString("HollowTetris", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal Symmetry.
        /// </summary>
        internal static string HorizontalSymmetry {
            get {
                return ResourceManager.GetString("HorizontalSymmetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added {0} Items..
        /// </summary>
        internal static string Info_AddItems {
            get {
                return ResourceManager.GetString("Info.AddItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please (use Ctrl) to select two decorations to combine them..
        /// </summary>
        internal static string Info_Combine {
            get {
                return ResourceManager.GetString("Info.Combine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the angle (clockwise) in degrees:.
        /// </summary>
        internal static string Info_EnterDegrees {
            get {
                return ResourceManager.GetString("Info.EnterDegrees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the scale factor of X:.
        /// </summary>
        internal static string Info_EnterXScale {
            get {
                return ResourceManager.GetString("Info.EnterXScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the scale factor of Y:.
        /// </summary>
        internal static string Info_EnterYScale {
            get {
                return ResourceManager.GetString("Info.EnterYScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a float scale factor (e.g., 2.0 or 0.5)..
        /// </summary>
        internal static string Info_FloatScale {
            get {
                return ResourceManager.GetString("Info.FloatScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot undo this..
        /// </summary>
        internal static string Info_NoUndo {
            get {
                return ResourceManager.GetString("Info.NoUndo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete .
        /// </summary>
        internal static string Info_ToDelete {
            get {
                return ResourceManager.GetString("Info.ToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadata.
        /// </summary>
        internal static string MetaData {
            get {
                return ResourceManager.GetString("MetaData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Property Shown.
        /// </summary>
        internal static string NoPropertyShown {
            get {
                return ResourceManager.GetString("NoPropertyShown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Painter.
        /// </summary>
        internal static string Painter {
            get {
                return ResourceManager.GetString("Painter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Painting Mode Control.
        /// </summary>
        internal static string PaintingModeControl {
            get {
                return ResourceManager.GetString("PaintingModeControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parallel Symmetry.
        /// </summary>
        internal static string ParallelSymmetry {
            get {
                return ResourceManager.GetString("ParallelSymmetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point.
        /// </summary>
        internal static string Point {
            get {
                return ResourceManager.GetString("Point", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pointer.
        /// </summary>
        internal static string Pointer {
            get {
                return ResourceManager.GetString("Pointer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puzzle Title.
        /// </summary>
        internal static string PuzzleTitle {
            get {
                return ResourceManager.GetString("PuzzleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo.
        /// </summary>
        internal static string Redo {
            get {
                return ResourceManager.GetString("Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ring.
        /// </summary>
        internal static string Ring {
            get {
                return ResourceManager.GetString("Ring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotational Symmetry.
        /// </summary>
        internal static string RotationalSymmetry {
            get {
                return ResourceManager.GetString("RotationalSymmetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Self Intersection.
        /// </summary>
        internal static string SelfIntersection {
            get {
                return ResourceManager.GetString("SelfIntersection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skew Hollow Tetris.
        /// </summary>
        internal static string SkewHollowTetris {
            get {
                return ResourceManager.GetString("SkewHollowTetris", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skew Tetris.
        /// </summary>
        internal static string SkewTetris {
            get {
                return ResourceManager.GetString("SkewTetris", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Square.
        /// </summary>
        internal static string Square {
            get {
                return ResourceManager.GetString("Square", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Star.
        /// </summary>
        internal static string Star {
            get {
                return ResourceManager.GetString("Star", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol.
        /// </summary>
        internal static string Symbol {
            get {
                return ResourceManager.GetString("Symbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tetris.
        /// </summary>
        internal static string Tetris {
            get {
                return ResourceManager.GetString("Tetris", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Three-way Symmetry.
        /// </summary>
        internal static string ThreeWaySymmetry {
            get {
                return ResourceManager.GetString("ThreeWaySymmetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Triangle 1.
        /// </summary>
        internal static string Triangle1 {
            get {
                return ResourceManager.GetString("Triangle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Triangle 2.
        /// </summary>
        internal static string Triangle2 {
            get {
                return ResourceManager.GetString("Triangle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Triangle 3.
        /// </summary>
        internal static string Triangle3 {
            get {
                return ResourceManager.GetString("Triangle3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Triangle 4.
        /// </summary>
        internal static string Triangle4 {
            get {
                return ResourceManager.GetString("Triangle4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Triangle 5.
        /// </summary>
        internal static string Triangle5 {
            get {
                return ResourceManager.GetString("Triangle5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        internal static string Undo {
            get {
                return ResourceManager.GetString("Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paint {0} with {1}..
        /// </summary>
        internal static string Undo_Paint {
            get {
                return ResourceManager.GetString("Undo.Paint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical Symmetry.
        /// </summary>
        internal static string VerticalSymmetry {
            get {
                return ResourceManager.GetString("VerticalSymmetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Warning] Corrupted Toolkit. Click YES to create a new one..
        /// </summary>
        internal static string Warnings_CorruptedToolkit {
            get {
                return ResourceManager.GetString("Warnings.CorruptedToolkit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Warning] Failed to load .
        /// </summary>
        internal static string Warnings_FailToLoad {
            get {
                return ResourceManager.GetString("Warnings.FailToLoad", resourceCulture);
            }
        }
    }
}
