//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WitnessVisualizer.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WitnessVisualizer.Resources.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 [Error] Please name the object using the text box. 的本地化字符串。
        /// </summary>
        internal static string Errors_NameEmpty {
            get {
                return ResourceManager.GetString("Errors.NameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [Error] Please select an edge first. 的本地化字符串。
        /// </summary>
        internal static string Errors_NoEdge {
            get {
                return ResourceManager.GetString("Errors.NoEdge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [Error] Please select at least an element first. 的本地化字符串。
        /// </summary>
        internal static string Errors_NoElement {
            get {
                return ResourceManager.GetString("Errors.NoElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [Error] Please select at least an tetris element first. 的本地化字符串。
        /// </summary>
        internal static string Errors_NoTetris {
            get {
                return ResourceManager.GetString("Errors.NoTetris", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hint 的本地化字符串。
        /// </summary>
        internal static string Hint {
            get {
                return ResourceManager.GetString("Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Added {0} Items. 的本地化字符串。
        /// </summary>
        internal static string Info_AddItems {
            get {
                return ResourceManager.GetString("Info.AddItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please (use Ctrl) to select two decorations to combine them. 的本地化字符串。
        /// </summary>
        internal static string Info_Combine {
            get {
                return ResourceManager.GetString("Info.Combine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enter the angle (clockwise) in degrees: 的本地化字符串。
        /// </summary>
        internal static string Info_EnterDegrees {
            get {
                return ResourceManager.GetString("Info.EnterDegrees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter a float scale factor (e.g., 2.0 or 0.5). 的本地化字符串。
        /// </summary>
        internal static string Info_FloatScale {
            get {
                return ResourceManager.GetString("Info.FloatScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You cannot undo this. 的本地化字符串。
        /// </summary>
        internal static string Info_NoUndo {
            get {
                return ResourceManager.GetString("Info.NoUndo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure you want to delete  的本地化字符串。
        /// </summary>
        internal static string Info_ToDelete {
            get {
                return ResourceManager.GetString("Info.ToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Metadata 的本地化字符串。
        /// </summary>
        internal static string MetaData {
            get {
                return ResourceManager.GetString("MetaData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No Property Shown 的本地化字符串。
        /// </summary>
        internal static string NoPropertyShown {
            get {
                return ResourceManager.GetString("NoPropertyShown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Painting Mode Control 的本地化字符串。
        /// </summary>
        internal static string PaintingModeControl {
            get {
                return ResourceManager.GetString("PaintingModeControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Puzzle Title 的本地化字符串。
        /// </summary>
        internal static string PuzzleTitle {
            get {
                return ResourceManager.GetString("PuzzleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Redo 的本地化字符串。
        /// </summary>
        internal static string Redo {
            get {
                return ResourceManager.GetString("Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Undo 的本地化字符串。
        /// </summary>
        internal static string Undo {
            get {
                return ResourceManager.GetString("Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Paint {0} with {1}. 的本地化字符串。
        /// </summary>
        internal static string Undo_Paint {
            get {
                return ResourceManager.GetString("Undo.Paint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Warning 的本地化字符串。
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [Warning] Corrupted Toolkit. Click YES to create a new one. 的本地化字符串。
        /// </summary>
        internal static string Warnings_CorruptedToolkit {
            get {
                return ResourceManager.GetString("Warnings.CorruptedToolkit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [Warning] Failed to load  的本地化字符串。
        /// </summary>
        internal static string Warnings_FailToLoad {
            get {
                return ResourceManager.GetString("Warnings.FailToLoad", resourceCulture);
            }
        }
    }
}
